intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import impl_libs += libhello%lib{hello}

lib{jsonxx}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs


# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_base"

# Export options.
#
lib{jsonxx}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" "-I$src_base"
  cxx.export.libs = $intf_libs
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{jsonxx}: bin.lib.version = @"-$version.project_id"
else
  lib{jsonxx}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the jsonxx/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
